export type Doctor = {
    name: string;
    education: string;
    post: string;
    experience: string;
    image?: string;
    slug: string;
    branch: string;
};

export const DOCTORS: Doctor[] = [
    {
        name: "Dr. Matham Charan Kumar",
        education: "BDS",
        post: "Dentist",
        experience: "20 Years Of Experience",
        image: "/docotr/charan.jpeg",
        slug: "dr-matham-charan-kumar",
        branch: "Kondapur",
    },
    {
        name: "Dr. Sushna Komuravelli",
        education: "MDS",
        post: "Prosthodontist",
        experience: "9 Years Of Experience",
        image: "/docotr/sushna.jpeg",
        slug: "dr-sushna-komuravelli",
        branch: "Kondapur",
    },
    {
        name: "Dr. N Sreevani",
        education: "BDS",
        post: "General Dentist",
        experience: "5 Years Of Experience",
        image: "/docotr/sreevani.jpeg",
        slug: "dr-n-sreevani",
        branch: "Kondapur",
    },
    {
        name: "Dr. B Dharanija",
        education: "BDS",
        post: "General Dentist",
        experience: "5 Years Of Experience",
        image: "/docotr/dharanija.jpeg",
        slug: "dr-b-dharanija",
        branch: "Kondapur",
    },
    {
        name: "Dr. Himasree Kasireddy",
        education: "MDS",
        post: "Endodontist",
        experience: "8 Years Of Experience",
        image: "/docotr/himasree.jpeg",
        slug: "dr-himasree-kasireddy",
        branch: "Kondapur",
    },
    {
        name: "Dr. Haneesh Mudra",
        education: "BDS",
        post: "General Dentist",
        experience: "9 Years Of Experience",
        image: "/docotr/haneesh.jpeg",
        slug: "dr-haneesh-mudra",
        branch: "Kondapur",
    },
    {
        name: "Dr. Borugadda Sujan Sekhar",
        education: "MDS",
        post: "Oral Surgeon",
        experience: "7 Years Of Experience",
        image: "/docotr/sujan.jpeg",
        slug: "dr-borugadda-sujan-sekhar",
        branch: "Kondapur",
    },
    {
        name: "Dr. Mounica",
        education: "MDS",
        post: "Orthodontist",
        experience: "9 Years Of Experience",
        image: "/docotr/mounika.jpeg",
        slug: "dr-mounica",
        branch: "Kondapur",
    },
    {
        name: "Dr. Manchana Ashok Kumar",
        education: "BDS",
        post: "General Dentist",
        experience: "20 Years Of Experience",
        image: "/docotr/ashok.jpeg",
        slug: "dr-manchana-ashok-kumar",
        branch: "KPHB",
    },
    {
        name: "Dr. Nagajyothi Namilikonda",
        education: "BDS",
        post: "General Dentist",
        experience: "10 Years Of Experience",
        image: "/docotr/naga.jpeg",
        slug: "dr-nagajyothi-namilikonda",
        branch: "KPHB",
    },
    {
        name: "Dr. Tarun Nalam",
        education: "BDS",
        post: "Implantologist",
        experience: "8 Years Of Experience",
        image: "/docotr/tarun.jpeg",
        slug: "dr-tarun-nalam",
        branch: "KPHB",
    },
    {
        name: "Dr. Sai Nikitha Arakari",
        education: "MDS",
        post: "Pedodontist",
        experience: "9 Years Of Experience",
        image: "/docotr/nititha.jpeg",
        slug: "dr-sai-nikitha-arakari",
        branch: "KPHB",
    },
    {
        name: "Dr. Malathi",
        education: "BDS",
        post: "Implantologist",
        experience: "19 Years Of Experience",
        image: "/docotr/malathi.jpeg",
        slug: "dr-malathi",
        branch: "KPHB",
    },
    {
        name: "Dr. E Santhosh Kumar",
        education: "MDS",
        post: "Oral And Maxillofacial Surgeon",
        experience: "13 Years Of Experience",
        image: "/docotr/santhosh.jpeg",
        slug: "dr-e-santhosh-kumar",
        branch: "Manikonda",
    },
    {
        name: "Dr. Ruchira Ganachari",
        education: "BDS",
        post: "General Dentist",
        experience: "8 Years Of Experience",
        image: "/docotr/ruchira.jpeg",
        slug: "dr-ruchira-ganachari",
        branch: "Manikonda",
    },
    {
        name: "Dr. Vani",
        education: "BDS",
        post: "General Dentist",
        experience: "8 Years Of Experience",
        image: "/docotr/vani.jpeg",
        slug: "dr-vani",
        branch: "Manikonda",
    },
    {
        name: "Dr. Suhaas Pradhyumna",
        education: "MDS",
        post: "Oral And Maxillofacial Surgeon",
        experience: "13 Years Of Experience",
        image: "/docotr/suhas.jpeg",
        slug: "dr-suhaas-pradhyumna",
        branch: "Banjara Hills",
    },
    {
        name: "Dr. Kaduluri Rajith",
        education: "BDS",
        post: "General Dentist",
        experience: "10 Years Of Experience",
        slug: "dr-kaduluri-rajith",
        branch: "Banjara Hills",
    },
    {
        name: "Dr. Satish P",
        education: "BDS",
        post: "General Dentist",
        experience: "7 Years Of Experience",
        image: "/docotr/satish.jpeg",
        slug: "dr-satish-p",
        branch: "Kompally",
    },
    {
        name: "Dr. Priyanka Reddy Pinninti",
        education: "BDS",
        post: "General Dentist",
        experience: "5 Years Of Experience",
        image: "/docotr/priyanka.jpeg",
        slug: "dr-priyanka-reddy-pinninti",
        branch: "Kompally",
    },
];
