export type Doctor = {
    name: string;
    education: string;
    post: string;
    experience: string;
    image?: string;
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    slug: string;
    phone: string;
    email: string;
    website: string;
    branch: string;
    consultationFee: string;
    visitingDays: string;
    visitingTime: string;
    languages: string[];
    medibuddyDiscount: string;
    expertise: string[];
};

export const DOCTORS: Doctor[] = [
    {
        name: "Dr. Matham Charan Kumar",
        education: "BDS",
        post: "Dentist",
        experience: "20 Years Of Experience",
        image: "/docotr/charan.jpeg",
        slug: "matham-charan-kumar",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "Every Day",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu", "Kannada"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Cavity evaluation and care.",
            "Dental treatment planning.",
            "Preventive oral care.",
            "Tooth pain assessment.",
            "Basic restorative dental care.",
        ],
    },
    {
        name: "Dr. Sushna Komuravelli",
        education: "MDS",
        post: "Prosthodontist",
        experience: "9 Years Of Experience",
        image: "/docotr/sushna.jpeg",
        slug: "sushna-komuravelli",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu", "Kannada"],
        medibuddyDiscount: "30%",
        expertise: [
            "Crowns and bridges.",
            "Dentures and tooth replacement.",
            "Dental implant restorations.",
            "Full mouth rehabilitation.",
            "Missing teeth assessment.",
            "Bite correction and function support.",
        ],
    },
    {
        name: "Dr. N Sreevani",
        education: "BDS",
        post: "General Dentist",
        experience: "5 Years Of Experience",
        image: "/docotr/sreevani.jpeg",
        slug: "n-sreevani",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10 AM–7 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Cavity detection and care.",
            "Teeth cleaning support.",
            "Preventive oral care.",
            "Tooth pain evaluation.",
            "Basic dental treatments.",
        ],
    },
    {
        name: "Dr. B Dharanija",
        education: "BDS",
        post: "General Dentist",
        experience: "5 Years Of Experience",
        image: "/docotr/dharanija.jpeg",
        slug: "b-dharanija",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "General dental consultations.",
            "Cavity care and fillings.",
            "Tooth pain assessment.",
            "Oral hygiene guidance.",
            "Preventive dental care.",
            "Basic restorative procedures.",
        ],
    },
    {
        name: "Dr. Himasree Kasireddy",
        education: "MDS",
        post: "Endodontist",
        experience: "8 Years Of Experience",
        image: "/docotr/himasree.jpeg",
        slug: "himasree-kasireddy",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Root canal treatment.",
            "Deep cavity management.",
            "Tooth pain diagnosis.",
            "Infected tooth care.",
            "Dental pulp treatment.",
            "Tooth preservation planning.",
        ],
    },
    {
        name: "Dr. Haneesh Mudra",
        education: "BDS",
        post: "General Dentist",
        experience: "9 Years Of Experience",
        image: "/docotr/haneesh.jpeg",
        slug: "haneesh-mudra",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Cavity evaluation and care.",
            "Tooth pain assessment.",
            "Preventive oral care.",
            "Basic dental treatment planning.",
            "General restorative procedures.",
        ],
    },
    {
        name: "Dr. Borugadda Sujan Sekhar",
        education: "MDS",
        post: "Oral Surgeon",
        experience: "7 Years Of Experience",
        image: "/docotr/sujan.jpeg",
        slug: "borugadda-sujan-sekhar",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10:30 AM–7:30 PM",
        languages: ["English", "Hindi", "Telugu", "Gujarathi"],
        medibuddyDiscount: "30%",
        expertise: [
            "Wisdom tooth removal.",
            "Tooth extractions.",
            "Oral surgical consultations.",
            "Impacted tooth evaluation.",
            "Jaw and facial pain assessment.",
            "Minor oral surgical procedures.",
        ],
    },
    {
        name: "Dr. Mounica",
        education: "MDS",
        post: "Orthodontist",
        experience: "9 Years Of Experience",
        image: "/docotr/mounika.jpeg",
        slug: "mounica",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kondapur",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–7 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Braces treatment.",
            "Clear aligner planning.",
            "Teeth alignment correction.",
            "Bite correction.",
            "Orthodontic consultations.",
            "Smile alignment assessment.",
        ],
    },
    {
        name: "Dr. Manchana Ashok Kumar",
        education: "BDS",
        post: "General Dentist",
        experience: "20 Years Of Experience",
        image: "/docotr/ashok.jpeg",
        slug: "manchana-ashok-kumar",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "KPHB",
        consultationFee: "₹300",
        visitingDays: "Every Day",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Tooth pain assessment.",
            "Cavity evaluation and care.",
            "Preventive oral care.",
            "Basic restorative procedures.",
            "General dental treatment planning.",
        ],
    },
    {
        name: "Dr. Nagajyothi Namilikonda",
        education: "BDS",
        post: "General Dentist",
        experience: "10 Years Of Experience",
        image: "/docotr/naga.jpeg",
        slug: "nagajyothi-namilikonda",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "KPHB",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10 AM–7 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "General dental consultations.",
            "Cavity detection and care.",
            "Teeth cleaning guidance.",
            "Tooth pain evaluation.",
            "Preventive dental care.",
            "Basic dental treatment planning.",
        ],
    },
    {
        name: "Dr. Tarun Nalam",
        education: "BDS",
        post: "Implantologist",
        experience: "8 Years Of Experience",
        image: "/docotr/tarun.jpeg",
        slug: "tarun-nalam",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "KPHB",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Dental implant consultations.",
            "Missing teeth evaluation.",
            "Implant treatment planning.",
            "Implant restoration support.",
            "Tooth replacement guidance.",
            "Oral health assessment before implants.",
        ],
    },
    {
        name: "Dr. Sai Nikitha Arakari",
        education: "MDS",
        post: "Pedodontist",
        experience: "9 Years Of Experience",
        image: "/docotr/nititha.jpeg",
        slug: "sai-nikitha-arakari",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "KPHB",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Kids dental check-ups.",
            "Pediatric cavity care.",
            "Preventive dental care for children.",
            "Milk tooth treatment guidance.",
            "Child-friendly dental consultations.",
            "Oral hygiene guidance for children.",
        ],
    },
    {
        name: "Dr. Malathi",
        education: "BDS",
        post: "Implantologist",
        experience: "19 Years Of Experience",
        image: "/docotr/malathi.jpeg",
        slug: "malathi",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "KPHB",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10 AM–5:30 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Dental implant consultations.",
            "Missing teeth assessment.",
            "Tooth replacement planning.",
            "General dental evaluation.",
            "Implant care guidance.",
            "Preventive oral care.",
        ],
    },
    {
        name: "Dr. E Santhosh Kumar",
        education: "MDS",
        post: "Oral And Maxillofacial Surgeon",
        experience: "13 Years Of Experience",
        image: "/docotr/santhosh.jpeg",
        slug: "e-santhosh-kumar",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Manikonda",
        consultationFee: "₹300",
        visitingDays: "Every Day",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Wisdom tooth removal.",
            "Tooth extractions.",
            "Oral and jaw surgery consultations.",
            "Impacted tooth evaluation.",
            "Facial and jaw pain assessment.",
            "Minor oral surgical procedures.",
        ],
    },
    {
        name: "Dr. Ruchira Ganachari",
        education: "BDS",
        post: "General Dentist",
        experience: "8 Years Of Experience",
        image: "/docotr/ruchira.jpeg",
        slug: "ruchira-ganachari",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Manikonda",
        consultationFee: "₹300",
        visitingDays: "Every Day",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Cavity evaluation and care.",
            "Tooth pain assessment.",
            "Preventive oral care.",
            "Basic restorative procedures.",
            "General dental treatment planning.",
        ],
    },
    {
        name: "Dr. Vani",
        education: "BDS",
        post: "General Dentist",
        experience: "8 Years Of Experience",
        image: "/docotr/vani.jpeg",
        slug: "vani",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Manikonda",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10:30 AM–7:30 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "General dental consultations.",
            "Cavity care and fillings.",
            "Tooth pain evaluation.",
            "Teeth cleaning guidance.",
            "Preventive dental care.",
            "Basic dental treatment planning.",
        ],
    },
    {
        name: "Dr. Suhaas Pradhyumna",
        education: "MDS",
        post: "Oral And Maxillofacial Surgeon",
        experience: "13 Years Of Experience",
        image: "/docotr/suhas.jpeg",
        slug: "suhaas-pradhyumna",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Banjara Hills",
        consultationFee: "₹300",
        visitingDays: "Every Day",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu", "Kannada"],
        medibuddyDiscount: "30%",
        expertise: [
            "Wisdom tooth removal.",
            "Tooth extractions.",
            "Oral surgery consultations.",
            "Impacted tooth evaluation.",
            "Jaw pain assessment.",
            "Minor oral surgical procedures.",
        ],
    },
    {
        name: "Dr. Kaduluri Rajith",
        education: "BDS",
        post: "General Dentist",
        experience: "10 Years Of Experience",
        slug: "kaduluri-rajith",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Banjara Hills",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10 AM–7 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Cavity evaluation and care.",
            "Tooth pain assessment.",
            "Preventive oral care.",
            "Basic restorative procedures.",
            "General dental treatment planning.",
        ],
    },
    {
        name: "Dr. Satish P",
        education: "BDS",
        post: "General Dentist",
        experience: "7 Years Of Experience",
        image: "/docotr/satish.jpeg",
        slug: "satish-p",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kompally",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "11 AM–8 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "General dental consultations.",
            "Cavity care and fillings.",
            "Tooth pain evaluation.",
            "Teeth cleaning guidance.",
            "Preventive dental care.",
            "Basic dental treatment planning.",
        ],
    },
    {
        name: "Dr. Priyanka Reddy Pinninti",
        education: "BDS",
        post: "General Dentist",
        experience: "5 Years Of Experience",
        image: "/docotr/priyanka.jpeg",
        slug: "priyanka-reddy-pinninti",
        phone: "+91 7799619994",
        email: "contact@eledenthospitals.com",
        website: "https://eledenthospitals.com/",
        branch: "Kompally",
        consultationFee: "₹300",
        visitingDays: "6 Days A Week",
        visitingTime: "10 AM–7 PM",
        languages: ["English", "Hindi", "Telugu"],
        medibuddyDiscount: "30%",
        expertise: [
            "Routine dental check-ups.",
            "Cavity detection and care.",
            "Tooth pain assessment.",
            "Oral hygiene guidance.",
            "Preventive dental care.",
            "Basic dental treatments.",
        ],
    },
];
